name: example
description: Example project for AppSize plugin
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  appsize:
    path: ../
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.1


flutter:
  uses-material-design: true
  assets:
    - images/